# SPDX-License-Identifier: GPL-2.0
#
# SPI Multi-IO 驱动

obj-$(CONFIG_SPI_MULTI_IO) += spi_multi_io.o

spi_multi_io-objs := \
	spi_multi_io_drv.o \
	spi_multi_io_core.o \
	spi_multi_io_init.o \
	spi_multi_io_ops.o \
	spi_multi_io_sysfs.o
