# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/
obj-$(CONFIG_AICDHD)   += aic8800/
obj-$(CONFIG_WLAN_NXP) += wlan_src/
obj-$(CONFIG_WLAN_RTL) += rtl8188eu/
obj-$(CONFIG_WLAN_RTL) += rtl8822bu/
