#ifndef __HYP_CONSTANTS_H__
#define __HYP_CONSTANTS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */

#define STRUCT_HYP_PAGE_SIZE 4 /* sizeof(struct hyp_page) */
#define PKVM_HYP_VM_SIZE 4448 /* sizeof(struct pkvm_hyp_vm) */
#define PKVM_HYP_VCPU_SIZE 9712 /* sizeof(struct pkvm_hyp_vcpu) */
#define STRUCT_HYP_BUFFER_PAGE_SIZE 32 /* sizeof(struct hyp_buffer_page) */

#endif
