dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3506b-cp2b-v10.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3506b-cp2b-uboot.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3506b-cp2b-p-v10.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3506b-cp2b-p-uboot.dtb